---
- name: Enable repo for i3-gaps and rofi
  command: dnf -y copr enable gregw/i3desktop


- name: Install i3 applications
  dnf:
    name:
      - i3-gaps
      - i3lock
      - i3status
      - rofi
      - dmenu
    state: latest

- name: Check if polybar is installed
  stat:
    path: /usr/local/bin/polybar
  register: stat_result

- name: Create source dir for polybar install
  file:
    dest: '{{ user_home }}/src/polybar'
    state: directory
  when: stat_result.stat.exists == False

- name: Pull polybar source
  git:
        repo: https://github.com/jaagr/polybar
        dest: '{{ user_home }}/src/polybar'
        version: 3.1.0
  when: stat_result.stat.exists == False

- name: Make polybar build dir
  file:
    dest: '{{ user_home }}/src/polybar/build'
    state: directory
  when: stat_result.stat.exists == False

- name: Build polybar
  shell: cmake ..
  args:
    chdir: '{{ user_home }}/src/polybar/build'
  when: stat_result.stat.exists == False

- name: Install polybar
  shell: make install
  args:
    chdir: '{{ user_home }}/src/polybar/build'
  become: yes
  when: stat_result.stat.exists == False

