---
- name: Enable repo for i3-gaps and rofi
  command: dnf -y copr enable gregw/i3desktop


- name: Install i3 applications
  dnf:
    name:
      - i3-gaps
      - i3lock
      - i3status
      - rofi
    state: latest

- name: Link rofi to dmenu
  file:
    src: '/usr/bin/rofi'
    dest: '/usr/bin/dmenu'
    state: link

- name: Create source dir for polybar install
  file:
    dest: '{{ user_home }}/src/polybar'
    state: directory

- name: Pull polybar source
  git:
        repo: https://github.com/jaagr/polybar
        dest: '{{ user_home }}/src/polybar'
        version: 3.1.0

- name: Make polybar build dir
  file:
    dest: '{{ user_home }}/src/polybar/build'
    state: directory

- name: Build polybar
  shell: cmake ..
  args:
    chdir: '{{ user_home }}/src/polybar/build'

- name: Install polybar
  shell: make install
  args:
    chdir: '{{ user_home }}/src/polybar/build'
  become: yes

