---
- name: Get dotfiles
  git:
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_dir }}'

- name: Link Xresources
  file:
    src: '{{ dotfiles_dir }}/Xresources'
    dest: '{{ user_home }}/.Xresources'
    state: link

- name: Link xinitrc
  file:
    src: '{{ dotfiles_dir }}/xinitrc'
    dest: '{{ user_home }}/.xinitrc'
    state: link

- name: Make i3 dir
  shell: mkdir -p {{ user_home }}/.config/i3

- name: Make polybar dir
  shell: mkdir -p {{ user_home }}/.config/polybar

- name: Ensure configs don't already exist
  file:
    dest:
      - '{{ user_home }}/.config/fish/config.fish'
      - '{{ user_home }}/.config/i3/config'
      - '{{ user_home }}/.config/polybar/config'
    state: absent

- name: Link fish config
  file:
    src: '{{ dotfiles_dir }}/fish/config.fish'
    dest: '{{ user_home }}/.config/fish/config.fish'
    state: link

- name: Link i3 config
  file:
    src: '{{ dotfiles_dir }}/i3/config'
    dest: '{{ user_home }}/.config/i3/config'
    state: link

- name: Link polybar config
  file:
    src: '{{ dotfiles_dir }}/polybar/config'
    dest: '{{ user_home }}/.config/polybar/config'
    state: link

- name: Copy polybar launcher
  copy:
    src: '{{ dotfiles_dir }}/polybar/launch.sh'
    dest: '{{ user_home }}/.config/polybar/launch.sh'
    mode: 0755
