---
- name: Get Oh My Fish installer
  get_url:
    url: https://get.oh-my.fish
    dest: '{{ user_home }}/install'
    mode: 0755

- name: Install Oh My Fish
  raw: fish install --path=~/.local/share/omf --config=~/.config/omf
  args:
    chdir: '{{ user_home }}'

- name: Install agnoster theme
  shell: omf install agnoster
  args:
    executable: /usr/bin/fish

- name: Apply agnoster theme
  shell: omf theme agnoster
  args:
    executable: /usr/bin/fish

- name: Install powerline dependencies
  pip:
    name:
      - psutil
      - hglib
      - bzr
      - pyuv
      - i3ipc
    extra_args: --user

- name: Install powerline
  pip:
    name: powerline-status
    extra_args: --user

- name: Install powerline fonts
  dnf:
    name: powerline-fonts
    state: latest

- name: Ensure fonts are loaded
  command: fc-cache -vf {{ user_home }}/.local/share/fonts/

- name: Create source dir for polybar install
  file:
    dest: '{{ user_home }}/src/polybar'
    state: directory

- name: Pull polybar source
  git:
        repo: https://github.com/jaagr/polybar
        dest: '{{ user_home }}/src/polybar'
        version: 3.1.0

- name: Make polybar build dir
  file:
    dest: '{{ user_home }}/src/polybar/build'

- name: Build polybar
  shell: cmake ..
  args:
    chdir: '{{ user_home }}/src/polybar/build'

- name: Install polybar
  shell: make install
  args:
    chdir: '{{ user_home }}/src/polybar/build'
  become: yes
