---
- name: Get Oh My Fish installer
  get_url:
    url: https://get.oh-my.fish
    dest: '{{ user_home }}/install'
    mode: 0755

#- name: Install Oh My Fish
#  raw: fish /home/cfutro/install --path=/home/cfutro/.local/share/omf --config=/home/cfutro/.config/omf

#- name: Install agnoster theme
#  shell: omf install agnoster
#  args:
#    executable: /usr/bin/fish

#- name: Apply agnoster theme
#  shell: omf theme agnoster
#  args:
#    executable: /usr/bin/fish

- name: Install powerline dependencies
  pip:
    name:
      - psutil
      - python-hglib
      - bzr
      - pyuv
      - i3ipc
    extra_args: --user

- name: Install powerline
  pip:
    name: powerline-status
    extra_args: --user

- name: Pull powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    dest: '{{ user_home }}/fonts'
    depth: 1

- name: Install powerline fonts
  shell: ./install.sh
  chdir: '{{ user_home }}/fonts'

- name: Ensure fonts are loaded
  command: fc-cache -vf {{ user_home }}/.local/share/fonts/
